### ISSUE TITLE
Content processor show_text NoMethodError for NilClass

### ISSUE THREAD

**Issue by joshco** [gettalong/hexapdf#117]
_(this is the same context as the colorspace issue we dealt with, in my redactor )_
The place it is failing on the line noted below.   The log lines saying 'show_text_string'  have the value of str.  It is when the string appears to be a single dash '-'.

````
rails_1_35fba6963d05 | [DEBUG] [fd6955] REDACT: show_text string  1RWH__WKLV_LV_IOLSSHG_IURP_RXU_GLVFXVVLRQ_LQ_WRGD\
rails_1_35fba6963d05 | [DEBUG] [fd6955]  V_PHHWLQJ___,W_QHHGV_WR_EH_WKLV_ZD\_WR_PDNH_WKH_WLPHOLQH_ZRUN_DQG_VR_SHRSOH_JH
W_WR nil? false blank? false
rails_1_35fba6963d05 | [DEBUG] [fd6955] REDACT: show_text string  NQRZ_ZKDW_FRPPLWWHHV_WKH\_DUH_PHPEHUV_RI_EHIRUH_WKRVH
_FRPPLWWHHV_PHHW_ nil? false blank? false
rails_1_35fba6963d05 | [DEBUG] [fd6955] REDACT: show_text string  - nil? false blank? false
rails_1_35fba6963d05 | [INFO ] [fd6955] method=GET  path=/story/
ontroller=story/articles action=view status=500  error='NoMethodError:undefined method `[]' for nil:NilClass'  duration=
881.97 db=0.00 uid=1  full_url=http://t
rails_1_35fba6963d05 | [FATAL] [fd6955]
rails_1_35fba6963d05 | [FATAL] [fd6955] NoMethodError (undefined  method `[]' for nil:NilClass):
rails_1_35fba6963d05 | [FATAL] [fd6955]    app/services/hexrep.rb:48:in `show_text'
rails_1_35fba6963d05 | [FATAL] [fd6955]    app/services/hexrep.rb:135:in `block in redact'
rails_1_35fba6963d05 | [FATAL] [fd6955]    app/services/hexrep.rb:130:in `with_index'
rails_1_35fba6963d05 | [FATAL] [fd6955]    app/services/hexrep.rb:130:in `redact'
````

__hexrep.rb__
````ruby

class Hexrep < HexaPDF::Content::Processor

  def initialize(page)
    super()
    @canvas = page.canvas(type: :overlay)
    @boxeslist = []
    @emails = []
    @strings = []
  end


  def show_text(str)

    begin
      strings = decode_text(str)
      @strings << strings
      boxes = decode_text_with_positioning(str) # Exception happens on this line, line 48
      boxes.each do |box|
        @boxeslist << box
      end
    rescue NoMethodError => ex
      Rails.logger.warn "PDF redact failure on string #{str}"
    end

  end

 #.........
````

**Comment by gettalong** [comment]
Can you share the PDF that produces the error? If it is confidential, you can send it to support@gettalong.at.

If you can't share it: Can you produce the actual line of the error? I.e. the line inside the HexaPDF library that throws this error?

**Comment by gettalong** [comment]
@joshco Since I didn't get any feedback on this problem, i can't investigate it. Therefore I will close this issue for now. If you have any further information, please add a comment and I will re-open the issue.
