### ISSUE TITLE
<NoMethodError: undefined method `oid' for nil:NilClass>

### ISSUE THREAD

**Issue by karosk9** [gettalong/hexapdf#119]
Hello, 
The problem with malformed pdf still occurs for me after gem bump. Before the latest release, I encountered a problem described in this issue: https://github.com/gettalong/hexapdf/issues/51. and got an error:

```
DF malformed around position : The oid,gen (43,0) values of the indirect object don't match the values (44,0) from the xref"
klass: "HexaPDF::MalformedPDFError"
title: "PDF malformed around position : The oid,gen (43,0) values of the indirect object don't match the values (44,0) from the xref"
```
After the version bump, it looks like some errors are indeed fixed but I still receive an error. The difference is that it’s triggered a couple of steps after the step that caused the problem before. 
At the moment I've got:
 
```
  NoMethodError: undefined method `oid' for nil:NilClass from /home/***/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/revision.rb:245:in `add_without_check'
```

The previous error clearly pointed to HexaPdf - so we could catch it and handle it. Now, when NoMethodError is returned it’s less safe.
Unfortunately, I can’t provide a pdf that causes the problem. Maybe the clue will be that it is a scanned pdf. An error is triggered by a method that adds an image to the canvas

```
    @canvas = page.canvas(type: :overlay)
```
and then the method that actually causes a problem
```
    @canvas.image(
      File.join('tmp', tmp_folder, "file_#{index}.png"),
      at: [@x_offset, @y_offset],
      height: (@image_height * @height).to_i,
      width: (@image_width * @width).to_i,
    )
```
more info:
`hexapdf inspect YOUR.PDF p` returns no error
```
page 1 (3,0): 2,0
page 2 (7,0): 6,0
page 3 (10,0): 9,0
page 4 (13,0): 12,0
page 5 (16,0): 15,0
page 6 (19,0): 18,0
page 7 (22,0): 21,0
page 8 (25,0): 24,0
page 9 (28,0): 27,0
page 10 (31,0): 30,0
page 11 (34,0): 33,0
page 12 (37,0): 36,0
page 13 (40,0): 39,0
page 14 (43,0): 42,0
```
I used an online tool to fix malformed pdf and for the fixed one output is the same, fixed document works well.

Here is a detailed backtrace of error:
```
[5] pry(main)> begin    
[5] pry(main)*   HexaPDF::Document.open(path_to_file) do |doc|      
[5] pry(main)*     doc.write('test1.pdf', validate: true)        
[5] pry(main)*   end        
[5] pry(main)* rescue => e      
[5] pry(main)*   e.inspect      
[5] pry(main)* end      
=> "#<NoMethodError: undefined method `oid' for nil:NilClass>"
```
```
[6] pry(main)> begin    
[6] pry(main)*   HexaPDF::Document.open(path_to file) do |doc|      
[6] pry(main)*     doc.write('test1.pdf', validate: true)        
[6] pry(main)*   end        
[6] pry(main)* rescue => e      
[6] pry(main)*   e.backtrace      
[6] pry(main)* end      
=> 
```

```
"/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/revision.rb:245:in `add_without_check'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/revision.rb:240:in `load_object'",
 "/home//.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/revision.rb:203:in `block in each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/utils/object_hash.rb:120:in `block in each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/utils/object_hash.rb:120:in `each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/utils/object_hash.rb:120:in `each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/revision.rb:201:in `each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:444:in `block in each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:443:in `reverse_each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:443:in `each'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:622:in `validate'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:665:in `write'",
 "(pry):61:in `block (2 levels) in <main>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:130:in `block in open'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:129:in `open'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:129:in `open'",
 "(pry):60:in `block in <main>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:77:in `block in repl'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:67:in `loop'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:67:in `repl'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:38:in `block in start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:38:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:15:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_class.rb:191:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:117:in `block in resume_pry'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:30:in `block (2 levels) in run'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/helpers/eval.rb:94:in `allowing_other_threads'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:30:in `block in run'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:29:in `catch'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:29:in `run'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:113:in `resume_pry'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:65:in `at_line'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/context.rb:98:in `at_line'",
 "(pry):39:in `block in <main>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:130:in `block in open'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:129:in `open'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/document.rb:129:in `open'",
 "(pry):37:in `<main>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:77:in `block in repl'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:67:in `loop'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:67:in `repl'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:38:in `block in start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:38:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:15:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_class.rb:191:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13:in `start_with_pry_byebug'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/console/console_command.rb:70:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/console/console_command.rb:19:in `start'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/console/console_command.rb:102:in `perform'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'",
 "/home/*****/projects/netguru/sovereignwealth/bin/rails:9:in `<top (required)>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/commands/rails.rb:6:in `call'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/command_wrapper.rb:38:in `call'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:215:in `block in serve'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
 "/home/*****/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
 "-e:1:in `<main>'"
```

**Comment by gettalong** [comment]
Thank for reporting this issue!

So the original error you were getting points to an actual problem with the PDF in question. This error triggers the new behaviour of reconstructing the main cross-reference table. It seems, however, that in this case this is not enough, or not correctly done.

The backtrace just shows where the error is happening and it tells us that `@loader.call(xref_entry)` will return `nil`. However, it is not clear to me why it returns `nil` at this point.

The best chance of getting to the root of the problem would be by analyzing the PDF that produces the error. If the PDF is confidential, I could sign a non-disclosure agreement. In this case please contact me at info@gettalong.at using your company e-mail address.

If you can't provide the PDF file, then I would need some more detailed information, like the contents of `xref_entry` at ` "/home/*****/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hexapdf-0.13.0/lib/hexapdf/revision.rb:240:in `load_object'",` and the output of `hexapdf inspect path_to_file r`.

**Comment by karosk9** [comment]
Hi, I am waiting for the document without sensitive data to be provided by the client and get back to you when I receive it.

**Comment by gettalong** [comment]
I got another bug report where a PDF produces the same kind of error and they provided the PDF. That PDF has a wrongly structured cross-reference table leading to this exception. As far as I can tell from the information you already provided, this is probably the same problem you are having.

I'm currently working on finding a work-around for correcting such invalid PDFs - will keep you posted!

**Comment by gettalong** [comment]
@karosk9 Could you please try out the devel branch (https://github.com/gettalong/hexapdf/tree/devel) if the latest changes fix your problem?

There is a high probability that those changes will fix your problem, too, since the error message is the same as with the other bug report.

**Comment by karosk9** [comment]
Hi! It works! :tada:

**Comment by gettalong** [comment]
Great to hear! And thanks for testing this out! This will be in the next release.
