### ISSUE TITLE
Can't use emojis in PDFs

### ISSUE THREAD

**Issue by enthusiasmus** [gettalong/hexapdf#121]
Dear hexapdf team,

I tried to use emojis (❤️) inside a PDF, but without success. Any ideas?

Code-Setup:
```
document = HexaPDF::Document.open(template_path(city))
document.fonts.add("Helvetica")
```

Error:
```
  1) PDF::Voucher.generate with emojis behaves like matches template pdf generates a pdf matching the template
     Failure/Error:
       layouter.fit([text_fragment(text: "❤", font: font)], 10, 10).draw(canvas, MARGIN, y_coordinate)
     
     HexaPDF::Error:
       Glyph for "❤" missing

     Shared Example Group: "matches template pdf" called from ./spec/lib/pdf/voucher_spec.rb:49
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/font/true_type_wrapper.rb:196:in `encode'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/content/canvas.rb:1751:in `block in show_glyphs_only'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/content/canvas.rb:1746:in `each'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/content/canvas.rb:1746:in `show_glyphs_only'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/text_fragment.rb:177:in `draw'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/text_layouter.rb:626:in `block (3 levels) in draw'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/line.rb:232:in `block in each'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/line.rb:222:in `each'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/line.rb:222:in `each'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/text_layouter.rb:624:in `block (2 levels) in draw'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/text_layouter.rb:621:in `each'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/text_layouter.rb:621:in `block in draw'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/content/canvas.rb:250:in `save_graphics_state'
     # /usr/local/bundle/gems/hexapdf-0.12.3/lib/hexapdf/layout/text_layouter.rb:618:in `draw'
     # ./app/lib/pdf/voucher.rb:75:in `add'
```

Gem-Version: 0.13.0
Ruby-Version: 2.6.6p146

Thanks in advance,
best regards,
Lukas

**Comment by gettalong** [comment]
You need to use a font that includes the needed emoji glyphs. The built-in fonts don't have emojis. Try for example GNU FreeFont (https://www.gnu.org/software/freefont/ranges/symbols.html) which appears to have emoji characters.

Please note that multi-color emojis are not supported (yet) because they are not stored as glyphs but as graphics.
