### ISSUE TITLE
Fuzzer + various crashes

### ISSUE THREAD

**Issue by bcoles** [gettalong/hexapdf#184]
Here's an extremely rudimentary naive fuzzer for `hexapdf` :

<details>

```ruby
#!/usr/bin/env ruby
####################################################
# ------------------------------------------------ #
# Fuzz HexaPDF Ruby gem with mutated PDF files     #
# ------------------------------------------------ #
#                                                  #
# Each test case is written to 'fuzz.pdf' in the   #
# current working directory.                       #
#                                                  #
# Crashes and the associated backtrace are saved   #
# in the 'crashes' directory in the current        #
# working directory.                               #
#                                                  #
####################################################
# ~ bcoles

require 'date'
require 'hexapdf'
require 'colorize'
require 'fileutils'
require 'timeout'
require 'securerandom'

VERBOSE = false
OUTPUT_DIR = "#{Dir.pwd}/crashes".freeze

#
# Show usage
#
def usage
  puts 'Usage: ./fuzz.rb <FILE1> [FILE2] [FILE3] [...]'
  puts 'Example: ./fuzz.rb test/data/**/*.pdf'
  exit 1
end

#
# Print status message
#
# @param [String] msg message to print
#
def print_status(msg = '')
  puts '[*] '.blue + msg if VERBOSE
end

#
# Print progress messages
#
# @param [String] msg message to print
#
def print_good(msg = '')
  puts '[+] '.green + msg if VERBOSE
end

#
# Print error message
#
# @param [String] msg message to print
#
def print_error(msg = '')
  puts '[-] '.red + msg
end

#
# Setup environment
#
def setup
  FileUtils.mkdir_p OUTPUT_DIR unless File.directory? OUTPUT_DIR
rescue => e
  print_error "Could not create output directory '#{OUTPUT_DIR}': #{e}"
  exit 1
end

#
# Generate a mutated PDF file with a single mitated byte
#
# @param [Path] f path to PDF file
#
def mutate_byte(f)
  data = IO.binread f
  position = SecureRandom.random_number data.size
  new_byte = SecureRandom.random_number 256
  new_data = data.dup.tap { |s| s.setbyte(position, new_byte) }

  File.open(@fuzz_outfile, 'w') do |file|
    file.write new_data
  end
end

#
# Generate a mutated PDF file with multiple mutated bytes
#
# @param [Path] f path to PDF file
#
def mutate_bytes(f)
  data = IO.binread f
  fuzz_factor = 200
  num_writes = rand((data.size / fuzz_factor.to_f).ceil) + 1

  new_data = data.dup
  num_writes.times do
    position = SecureRandom.random_number data.size
    new_byte = SecureRandom.random_number 256
    new_data.tap { |stream| stream.setbyte position, new_byte }
  end

  File.open(@fuzz_outfile, 'w') do |file|
    file.write new_data
  end
end

#
# Generate a mutated PDF file with all integers replaced by '-1'
#
# @param [Path] f path to PDF file
#
def clobber_integers(f)
  data = IO.binread f
  new_data = data.dup.gsub(/\d/, '-1')

  File.open(@fuzz_outfile, 'w') do |file|
    file.write new_data
  end
end

#
# Generate a mutated PDF file with all strings 3 characters or longer
# replaced with 2000 'A' characters
#
# @param [Path] f path to PDF file
#
def clobber_strings(f)
  data = IO.binread(f)
  new_data = data.dup.gsub(/[a-zA-Z]{3,}/, 'A' * 2000)

  File.open(@fuzz_outfile, 'w') do |file|
    file.write new_data
  end
end

#
# Read a PDF file
#
# @param [String] f path to PDF file
#
def read(f)
  print_status "Processing '#{f}'"
  begin
    pdf = HexaPDF::Document.open(f)
  rescue HexaPDF::Error
    print_status "Could not parse PDF '#{f}': PDF is malformed"
    return
  end
  print_good 'Processing complete'

  print_status "Parsing '#{f}'"
  begin
    parse(pdf)
  rescue HexaPDF::Error
    print_status "Could not parse PDF '#{f}': PDF is malformed"
    return
  end

  print_good 'Parsing complete'
end

#
# Parse PDF
#
# @param [HexaPDF::Document] pdf HexaPDF PDF Document
#
def parse(pdf)
  print_status 'Parsing PDF contents...'

  pdf.clear_cache
  pdf.pages
  pdf.images
  pdf.files
  pdf.fonts
  pdf.destinations
  pdf.trailer
  pdf.catalog
  pdf.version
  pdf.encrypted?
  pdf.security_handler
  pdf.signed?
  pdf.signatures
  pdf.validate

  pdf.pages.each do |p|
  end
  pdf.images.each do |i|
  end
  pdf.files.each do |f|
  end
end

#
# Show summary of crashes
#
def summary
  puts
  puts "Complete! Crashes saved to '#{OUTPUT_DIR}'"
  puts
  puts `/usr/bin/head -n1 #{OUTPUT_DIR}/*.trace` if File.exist? '/usr/bin/head'
end

#
# Report error message to STDOUT
# and save fuzz test case and backtrace to OUTPUT_DIR
#
def report_crash(e)
  puts " - #{e.message}"
  puts e.backtrace.first
  fname = "#{DateTime.now.strftime('%Y%m%d%H%M%S%N')}_crash_#{rand(1000)}"
  FileUtils.mv @fuzz_outfile, "#{OUTPUT_DIR}/#{fname}.pdf"
  File.open("#{OUTPUT_DIR}/#{fname}.pdf.trace", 'w') do |file|
    file.write "#{e.message}\n#{e.backtrace.join "\n"}"
  end
end

#
# Test HexaPDF with the mutated file
#
def test
  Timeout.timeout(@timeout) do
    read(@fuzz_outfile)
  end
rescue SystemStackError => e
  report_crash e
rescue Timeout::Error => e
  report_crash e
rescue SyntaxError => e
  report_crash e
rescue => e
  raise e unless e.backtrace.join("\n") =~ %r{hexapdf}
  report_crash e
end

#
# Generate random byte mutations and run test
#
# @param [String] f path to PDF file
#
def fuzz_bytes(f)
  iterations = 1000
  1.upto(iterations) do |i|
    print "\r#{(i * 100) / iterations} % (#{i} / #{iterations})"
    mutate_bytes f
    test
  end
end

#
# Generate integer mutations and run tests
#
# @param [String] f path to PDF file
#
def fuzz_integers(f)
  clobber_integers f
  test
end

#
# Generate string mutations and run tests
#
# @param [String] f path to PDF file
#
def fuzz_strings(f)
  clobber_strings f
  test
end

puts '-' * 60
puts '% Fuzzer for HexaPDF Ruby gem'
puts '-' * 60
puts

usage if ARGV[0].nil?

setup

@timeout = 15
@fuzz_outfile = 'fuzz.pdf'

trap 'SIGINT' do
  puts
  puts 'Caught interrupt. Exiting...'
  summary
  exit 130
end

ARGV.each do |f|
  unless File.exist? f
    print_error "Could not find file '#{f}'"
    next
  end

  fuzz_integers f
  fuzz_strings f
  fuzz_bytes f

  puts '-' * 60
end

summary
```
</details>

Here's the stack traces for the latest version on `master` using [./test/data/**/*.pdf](https://github.com/gettalong/hexapdf/tree/master/test/data) as input.

[crashes.zip](https://github.com/gettalong/hexapdf/files/8791607/crashes.zip)

Unique crash locations:

```
$ head -n 2 crashes/*.trace | grep ":in " | sort -u 
<internal:pack>:134:in `pack'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/document/pages.rb:131:in `each'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/document.rb:519:in `[]'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/fast_aes.rb:76:in `update'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/security_handler.rb:209:in `[]'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/security_handler.rb:509:in `key_length'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/standard_security_handler.rb:382:in `+'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/standard_security_handler.rb:520:in `user_password_valid?'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/standard_security_handler.rb:522:in `user_password_valid?'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/standard_security_handler.rb:533:in `owner_password_valid?'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/encryption/standard_security_handler.rb:74:in `perform_validation'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/rectangle.rb:124:in `after_data_change'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/tokenizer.rb:432:in `seek'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/type/page.rb:171:in `[]'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/type/page_tree_node.rb:225:in `block in each_page'
/var/lib/gems/2.7.0/gems/hexapdf-0.23.0/lib/hexapdf/type/page_tree_node.rb:228:in `block in each_page'
```

**Comment by gettalong** [comment]
Thanks, this looks interesting. I will have to see what could be done about the crashes.

**Comment by gettalong** [comment]
@bcoles Hmm... after looking a bit into this I'm not sure if there is much to do here. If by fuzzing you create an invalid PDF, I think it is okay that HexaPDF crashes. What would be your suggestion?

**Comment by bcoles** [comment]
Hey. I didn't look much into the results. I was fuzzing whichever libraries GitHub recommend to me.


> If by fuzzing you create an invalid PDF, I think it is okay that HexaPDF crashes.

The fuzzer explicitly ignores `HexaPDF::Error`  exceptions. All errors raised above were not handled gracefully and did not raise a `HexaPDF::Error`. Software using this library and only rescuing `HexaPDF::Error` would crash.

It is entirely expected that a fuzzer will find crashes. The idea is to identify and resolve bugs before they become a problem.

It is my hope - perhaps unwarranted - that some of the crashes would be legitimate bugs worth fixing.

For what it is worth, other PDF libraries I've fuzzed have had resource exhaustion denial of service bugs which caused the process to hang with 100% CPU. Glancing at the stack traces above, it seems that HexaPDF didn't have this issue. So that's good.

> What would be your suggestion?

Where possible, handle the errors gracefully and raise `HexaPDF::Error`  with a suitable message.

**Comment by gettalong** [comment]
Thanks for the input. I will see if I can find any really problematic cases. However, I think I will defer error handling to the application using HexaPDF since handling all such errors in HexaPDF would make it quite unwieldy.

**Comment by gettalong** [comment]
Nothing really to do here since handling of unexpected errors is delegated to the application/library using HexaPDF.
