### ISSUE TITLE
 HexaPDF::Content::Processor  undefined method `glyph_scaling_factor'

### ISSUE THREAD

**Issue by NelsonDocsketch** [gettalong/hexapdf#302]
Hi @gettalong i'm currently having the following error while using the content processor with an specific file, it looks like a font issue because when i tried to edit the file with adobe acrobat, it complained about the file encoding. It started working after saving it, can't share the original file.

```
require 'hexapdf'

path = 'output.pdf'

document = HexaPDF::Document.open(ARGV[0])

document.pages.each do |page|
  processor  = HexaPDF::Content::Processor.new(page)
  page.process_contents(processor)
end

```

```
 /hexapdf-0.40.0/lib/hexapdf/content/graphics_state.rb:732:in `update_scaled_font_size': undefined method `glyph_scaling_factor' for {:BaseFont=>:Helvetica, :Encoding=>:WinAnsiEncoding, :Name=>:F1, :Subtype=>:Type1, :Type=>:Font}:Hash (NoMethodError)

        @scaled_font_size = @font_size * (@font&.glyph_scaling_factor || 0.001) *
                                               ^^^^^^^^^^^^^^^^^^^^^^
	from  /hexapdf-0.40.0/lib/hexapdf/content/graphics_state.rb:685:in `font='
from  /hexapdf-0.40.0/lib/hexapdf/content/operator.rb:767:in `invoke'
	from  /hexapdf-0.40.0/lib/hexapdf/content/processor.rb:361:in `process'
	from  /hexapdf-0.40.0/lib/hexapdf/content/parser.rb:192:in `block in parse'
from  /hexapdf-0.40.0/lib/hexapdf/content/parser.rb:186:in `loop'
	from  /hexapdf-0.40.0/lib/hexapdf/content/parser.rb:186:in `parse'
	from  /hexapdf-0.40.0/lib/hexapdf/content/parser.rb:166:in `parse'
from  /hexapdf-0.40.0/lib/hexapdf/type/page.rb:393:in `process_contents'
	from hexapdf_error.rb:9:in `block in <main>'
	from  /hexapdf-0.40.0/lib/hexapdf/type/page_tree_node.rb:243:in `block in each_page'
from  /hexapdf-0.40.0/lib/hexapdf/pdf_array.rb:183:in `block in each'
	from  /hexapdf-0.40.0/lib/hexapdf/pdf_array.rb:183:in `each_index'
	from  /hexapdf-0.40.0/lib/hexapdf/pdf_array.rb:183:in `each'
from  /hexapdf-0.40.0/lib/hexapdf/type/page_tree_node.rb:241:in `each_page'
	from  /hexapdf-0.40.0/lib/hexapdf/document/pages.rb:178:in `each'
	from hexapdf_error.rb:7:in `<main>'
```

Thanks for your help on this.

**Comment by gettalong** [comment]
From the stack trace it seems that HexaPDF doesn't correctly map the font dictionary object to the correct class. Alas, it is hard to identify the problem with the file.

Could you run `hexapdf info --check file.pdf` and post the output?

**Comment by NelsonDocsketch** [comment]
Sure thing.

```
WARNING: Validation error for trailer: ID field should always be set (correctable)
WARNING: Validation error for sub-object of object type XObject (11,0): Field SMask requires document version to be 1.4 (correctable)
File name:          original.pdf
File size:          334802 bytes
Producer:           PyPDF3
Pages:              4
Version:            1.4
```

**Comment by gettalong** [comment]
Thanks for the output! Alas, it doesn't report anything out of the ordinary.

Could you please run `hexapdf inspect original.pdf search Helvetica rev pages po 1 po 2 po 3 po 4` and post the output?

And if possible also `hexapdf inspect original.pdf r`?

Thanks!

**Comment by gettalong** [comment]
@NelsonDocsketch Thanks! I think I found the problem. Could you please try the devel branch with your PDF file?

**Comment by NelsonDocsketch** [comment]
@gettalong Sorry for taking too long, i just tried and that worked!

**Comment by gettalong** [comment]
No problem and thanks for testing! I will release a new version with the fix later this week.
