### ISSUE TITLE
NoMethodError for nil when accessing stream in a PDF's content streams

### ISSUE THREAD

**Issue by RibeiroPintoPatrick** [gettalong/hexapdf#334]
First, I want to thank you for developing and maintaining HexaPDF. It's an incredibly powerful tool that has made working with PDFs in Ruby much easier. I truly appreciate all the work you've put into it!

I've encountered a `NoMethodError` when trying to access the content streams of a page in a PDF document. It seems that one of the content streams in the `:Contents` array is `nil`, which causes the error when calling the stream method.

**Steps to Reproduce:**

1. Use the following code to open a PDF and try accessing the contents of the first page:

```ruby
require 'hexapdf'

pdf = HexaPDF::Document.open("path/to/file.pdf")
pdf.pages.first.contents
```

2. When running the above code, the following error is raised:

```
/Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/hexapdf-0.46.0/lib/hexapdf/type/page.rb:361:in `block in contents': undefined method `stream' for nil (NoMethodError)

          content << content_stream.stream
                                   ^^^^^^^
        from /Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/hexapdf-0.46.0/lib/hexapdf/type/page.rb:359:in `each'
        from /Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/hexapdf-0.46.0/lib/hexapdf/type/page.rb:359:in `each_with_object'
        from /Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/hexapdf-0.46.0/lib/hexapdf/type/page.rb:359:in `contents'
        from (irb):3:in `<main>'
        from <internal:kernel>:187:in `loop'
        from /Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/irb-1.14.1/exe/irb:9:in `<top (required)>'
        from /Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/bin/irb:25:in `load'
        from /Users/ribeiropintopatrick/.asdf/installs/ruby/3.3.5/bin/irb:25:in `<main>'
```

**Analyse the `:Contents` array:**

Code:
```ruby
pdf.pages.first[:Contents].value
```
Output:
```ruby
[#<HexaPDF::Stream [1, 0] value={:Length=>40}>,
 #<HexaPDF::Stream [2, 0] value={:Length=>40}>,
 #<HexaPDF::Stream [3, 0] value={:Length=>40}>,
 #<HexaPDF::Stream [4, 0] value={:Length=>40}>,
 #<HexaPDF::Stream [5, 0] value={:Length=>40}>,
 #<HexaPDF::Stream [6, 0] value={:Length=>39}>,
 #<HexaPDF::Stream [9, 0] value={:Length=>41}>,
..........
 #<HexaPDF::Stream [202, 0] value={:Length=>48}>,
 #<HexaPDF::Stream [203, 0] value={:Length=>88}>,
 #<HexaPDF::Stream [204, 0] value={:Length=>46}>,
 #<HexaPDF::Stream [205, 0] value={:Length=>39}>,
 #<HexaPDF::Stream [206, 0] value={:Length=>48}>,
 #<HexaPDF::Stream [207, 0] value={:Length=>46}>,
 #<HexaPDF::Stream [208, 0] value={:Length=>78}>,
 nil,
 #<HexaPDF::Stream [209, 0] value={:Length=>53}>,
 #<HexaPDF::Stream [210, 0] value={:Length=>50}>,
 #<HexaPDF::Stream [211, 0] value={:Length=>56}>,
 #<HexaPDF::Stream [212, 0] value={:Length=>56}>,
 #<HexaPDF::Stream [213, 0] value={:Length=>54}>,
 #<HexaPDF::Stream [214, 0] value={:Length=>50}>,
 #<HexaPDF::Stream [215, 0] value={:Length=>50}>,
..........
```

Thank you for your assistance.

**Comment by gettalong** [comment]
Thanks for reporting! And ah, the joys of all the ways a PDF document might be (mis)constructed :grin: I'm really wondering why somebody/some library would generate hundreds of partial and very small content streams for a single page :thinking: The only situation in which HexaPDF does add two such small content streams is when using an overlay/underlay canvas.

Anyway, this will be fixed for the next release.

**Comment by gettalong** [comment]
Fixed in the devel branch, next release will be in about a week.

**Comment by RibeiroPintoPatrick** [comment]
Thank you very much for the quick response and the fix, @gettalong!
