### ISSUE TITLE
Bug in Flattening pdf

### ISSUE THREAD

**Issue by FabianVorhauser** [gettalong/hexapdf#340]
Hello, 
so i wanna fill a pdf with forms using python, but after doing that flattening doesnt work. Not with python but also not with ruby and hexapdf. The thing is that if i do something manually to the filled pdf for example add a number in a field and safe it hexapdf works. 
Hope for help
Thanks.

Python code:

~~~ python
import subprocess
import sys
from fillpdf import fillpdfs
import fitz  # PyMuPDF für die PDF-Finalisierung

# Pfad zur Eingabe-PDF und Ausgabe-PDF
input_pdf = r"S:\A_dis\USER\Fabian\04_Python\PDF Titelblatt\orig.pdf"
output_pdf = r"S:\A_dis\USER\Fabian\04_Python\PDF Titelblatt\orig_filled.pdf"
final_pdf = r"S:\A_dis\USER\Fabian\04_Python\PDF Titelblatt\orig_filled_finalized.pdf"
flattened_pdf = r"S:\A_dis\USER\Fabian\04_Python\PDF Titelblatt\orig_filled_flattened.pdf"

# Daten zum Ausfüllen des Formulars (dieses Dictionary wird verwendet, um Felder zu füllen)
data_dict = {
    'Bauherr': 'FV',  # Beispiel: Ersetze 'Bauherr' mit dem tatsächlichen Feldnamen
    #'Name': 'Max Mustermann',  # Beispiel: weiteres Feld ausfüllen
}

def finalize_pdf(input_pdf, output_pdf):
    """
    Finalisiert die PDF nach dem Ausfüllen der Felder, um sicherzustellen, dass alle
    Erscheinungsbilder (Appearances) korrekt gespeichert werden.
    """
    # Öffne die PDF-Datei mit PyMuPDF
    doc = fitz.open(input_pdf)
    
    # Speichere das PDF mit den aktuellen Änderungen (stellt sicher, dass alle Formulardaten abgeschlossen sind)
    doc.save(output_pdf)

def flatten_pdf(input_pdf, output_pdf):
    """
    Führen Sie das Flattening der PDF mit HexaPDF über ein Ruby-Skript aus.
    """
    # Stelle sicher, dass das HexaPDF Ruby-Skript aufgerufen wird, um die PDF zu flatten.
    hexapdf_command = [
        r'C:\Ruby33-x64\bin\hexapdf.bat', 'form', '--flatten', input_pdf, output_pdf
    ]
    
    try:
        # Führe das HexaPDF-Tool aus und warte auf die Beendigung
        subprocess.run(hexapdf_command, check=True)
        print(f"Das Flattening wurde erfolgreich durchgeführt: {output_pdf}")
    except subprocess.CalledProcessError as e:
        print(f"Fehler beim Flattening der PDF: {e}")

# Formular ausfüllen
fillpdfs.write_fillable_pdf(input_pdf, output_pdf, data_dict)
print(f"Die ausgefüllte PDF wurde unter {output_pdf} gespeichert.")

# Finalisieren der ausgefüllten PDF
finalize_pdf(output_pdf, final_pdf)
print(f"Die PDF wurde finalisiert und unter {final_pdf} gespeichert.")

# Flattening der finalisierten PDF durchführen
flatten_pdf(final_pdf, flattened_pdf)
~~~

Error:

~~~
Problem encountered: undefined method `normal_appearance' for an instance of String
Backtrace (last 10 lines):
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/annotation.rb:234:in `appearance'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/acro_form/text_field.rb:234:in `block in create_appearances'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/acro_form/field.rb:294:in `block in each_widget'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/pdf_array.rb:183:in `block in each'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/pdf_array.rb:183:in `each_index'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/pdf_array.rb:183:in `each'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/acro_form/field.rb:294:in `each_widget'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/acro_form/text_field.rb:229:in `create_appearances'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/acro_form/form.rb:487:in `block in flatten'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/hexapdf-1.0.3/lib/hexapdf/type/acro_form/form.rb:487:in `each'
[Uploading orig_filled.pdf…]()
~~~

**Comment by gettalong** [comment]
The original PDF file didn't finish uploading before you created the issue and is therefore not available. Could you please edit the issue description and add a link to the original PDF?

**Comment by gettalong** [comment]
@FabianVorhauser I will close this issue. Please use the current version of HexaPDF (it seems you are still using 1.0.3) and try again or provide the original PDF so that I can have a further look.
