### ISSUE TITLE
undefined method `[]' for #<HexaPDF::Object [12, 0] value=[:Pattern, :DeviceRGB]>

### ISSUE THREAD

**Issue by Phillita** [gettalong/hexapdf#7]
Hello! I'm having issues inserting images into a merged HexaPDF document.

Context:
I'm currently creating a new HexaPDF document and then creating a couple pages with it (title page/table of contents) and am then merging pdf's into this document. 
The last step is where I then loop every page of the document and add a header/footer. Here is where my issue starts. When I try to insert an image into the header or footer, it gives me the error message ```undefined method `[]' for #<HexaPDF::Object [12, 0] value=[:Pattern, :DeviceRGB]>```.

After debugging the code, I had made it through the image insert to this block of code within the `DocumentUtils`:

```
def each_image(&block)
        images = @document.each(current: false).select do |obj|
          next unless obj.kind_of?(HexaPDF::Dictionary)
          obj[:Subtype] == :Image && !obj[:ImageMask]
        end
        masks = images.each_with_object([]) do |image, temp|
          temp << image[:Mask] if image[:Mask].kind_of?(Stream)
          temp << image[:SMask] if image[:SMask].kind_of?(Stream)
        end
        (images - masks).each(&block)
      end
```

And the failure comes from this lie: `obj[:Subtype] == :Image && !obj[:ImageMask]`

The thing is, I tried running the lines directly after this loop and the image gets inserted into the document correctly. 

Any help here would be much appreciated!

**Comment by gettalong** [comment]
I'm not really sure I understand what you are doing. Would it be possible for you to show me the code that you've written? And the full backtrace?

**Comment by Phillita** [comment]
Sorry for the very delayed response!

I had to simplify my code a bit here. 
In order for the code to execute, you will need to replace the different file paths so that they match your system.

The PDF's that have been attached here are generated from HTML via pdfkit. I've also used PDF's that were generated from wicked_pdf and they fail with the same issue below.

[pdf1.pdf](https://github.com/gettalong/hexapdf/files/575776/pdf1.pdf)
[pdf2.pdf](https://github.com/gettalong/hexapdf/files/575777/pdf2.pdf)
![example-logo-2](https://cloud.githubusercontent.com/assets/1016928/20063705/344374b0-a4d6-11e6-8efe-f881f1e87214.png)
![example-logo](https://cloud.githubusercontent.com/assets/1016928/20063703/34388c12-a4d6-11e6-8004-59c8c50d708a.png)
![doc-title-page](https://cloud.githubusercontent.com/assets/1016928/20063704/343cc2fa-a4d6-11e6-8178-a98cddc7f32e.png)

```
load(File.join('/', 'Users', 'tphillips', 'Desktop', 'hexa-issue', 'example-code.rb'))
create
```

Stack Trace from the code:

```
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document_utils.rb:88:in `block in each_image'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document.rb:395:in `block (2 levels) in each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/revision.rb:178:in `block in each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/utils/object_hash.rb:117:in `block in each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/utils/object_hash.rb:117:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/utils/object_hash.rb:117:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/revision.rb:178:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document.rb:393:in `block in each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document.rb:392:in `reverse_each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document.rb:392:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document_utils.rb:87:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document_utils.rb:87:in `select'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document_utils.rb:87:in `each_image'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/document_utils.rb:69:in `add_image'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/content/canvas.rb:1261:in `xobject'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:77:in `add_header'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:60:in `block in stamp_pages'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/type/page_tree_node.rb:206:in `block in each_page'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/type/page_tree_node.rb:203:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/type/page_tree_node.rb:203:in `each_page'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:55:in `stamp_pages'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:13:in `create'
(pry):2:in `<main>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:323:in `handle_line'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:77:in `block in repl'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `call'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-byebug-3.2.0/lib/pry-byebug/pry_ext.rb:15:in `start_with_pry_byebug'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/Users/tphillips/rails/mypolicies/bin/rails:8:in `<top (required)>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'

/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:80:in `rescue in add_header'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:70:in `add_header'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:60:in `block in stamp_pages'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/type/page_tree_node.rb:206:in `block in each_page'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/type/page_tree_node.rb:203:in `each'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/hexapdf-0.1.0/lib/hexapdf/type/page_tree_node.rb:203:in `each_page'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:55:in `stamp_pages'
/Users/tphillips/Desktop/Support Docs/tmp/hexa-support stuff/example-code.rb:13:in `create'
(pry):2:in `<main>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:323:in `handle_line'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:77:in `block in repl'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `call'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pry-byebug-3.2.0/lib/pry-byebug/pry_ext.rb:15:in `start_with_pry_byebug'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/skylight-0.10.2/lib/skylight/probes.rb:81:in `require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/Users/tphillips/rails/mypolicies/bin/rails:8:in `<top (required)>'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/tphillips/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
=> nil
```

**Comment by gettalong** [comment]
@Phillita Thanks for the stack trace, this problem has already been fixed, see commit https://github.com/gettalong/hexapdf/commit/dcfe63d43abb672efa6f12fc3bf2d05fa9005e1c. So if you use the latest version on Github, it should work fine.

**Comment by Phillita** [comment]
I'm currently using gem version `hexapdf (0.1.0)`
Is there another version that hasn't been posted?

**Comment by gettalong** [comment]
@Phillita I have pushed changes to the Github repository but haven't released a new gem. So if you use the latest code that is available on Github it will work fine.
