### ISSUE TITLE
Type of field Subtype is invalid

### ISSUE THREAD

**Issue by iamjohnford** [gettalong/hexapdf#79]
Another one of my tests has been with removing embedded movies from a PDF. I had no idea you could embed multimedia into a PDF until recently. Not an urgent issue but something I wanted to mention in case it's worth fixing.

**Test File**

[test-movie.pdf](https://github.com/gettalong/hexapdf/files/3627133/test-movie.pdf)

**Code**

```ruby
require 'hexapdf'
doc = HexaPDF::Document.open('test-movie.pdf')
doc.write('output.pdf')
```

**Trace**

```
Traceback (most recent call last):
	23: from lib/hexapdf/document.rb:628:in `write'
	22: from lib/hexapdf/document.rb:584:in `validate'
	21: from lib/hexapdf/document.rb:412:in `each'
	20: from lib/hexapdf/document.rb:412:in `reverse_each'
	19: from lib/hexapdf/document.rb:413:in `block in each'
	18: from lib/hexapdf/revision.rb:186:in `each'
	17: from lib/hexapdf/utils/object_hash.rb:120:in `each'
	16: from lib/hexapdf/utils/object_hash.rb:120:in `each'
	15: from lib/hexapdf/utils/object_hash.rb:120:in `block in each'
	14: from lib/hexapdf/revision.rb:188:in `block in each'
	13: from lib/hexapdf/document.rb:415:in `block (2 levels) in each'
	12: from lib/hexapdf/document.rb:586:in `block in validate'
	11: from lib/hexapdf/object.rb:270:in `validate'
	10: from lib/hexapdf/object.rb:270:in `catch'
	 9: from lib/hexapdf/object.rb:271:in `block in validate'
	 8: from lib/hexapdf/stream.rb:285:in `perform_validation'
	 7: from lib/hexapdf/dictionary.rb:264:in `perform_validation'
	 6: from lib/hexapdf/dictionary.rb:255:in `each_set_key_or_required_field'
	 5: from lib/hexapdf/dictionary.rb:255:in `each_key'
	 4: from lib/hexapdf/dictionary.rb:255:in `block in each_set_key_or_required_field'
	 3: from lib/hexapdf/dictionary.rb:288:in `block in perform_validation'
	 2: from lib/hexapdf/object.rb:272:in `block (2 levels) in validate'
	 1: from lib/hexapdf/document.rb:581:in `block in validate'
lib/hexapdf/document.rb:630:in `block in write': Validation error for (18,0): Type of field Subtype is invalid: String (HexaPDF::Error)
```

**Comment by gettalong** [comment]
Thanks for reporting this problem!

I looked at it and the result of inspecting object (18,0) is:

~~~
<<
  /Type /EmbeddedFile
  /Subtype (application/x-shockwave-flash)
  /Length 1825
>>
~~~

The `/Subtype` key has a String object as value but the PDF 1.7 specification says it has to be a Name (=Symbol) object - see section 7.11.4.1 of the spec. So in this case there is really a problem with the PDF file itself.

However, since Name objects are essentially strings and vice versa, I will see if this validation problem can be automatically corrected by converting the value to the right type.

**Comment by gettalong** [comment]
I have changed the validation feature to correct such problems - you can test with the latest repo version.
