### ISSUE TITLE
NoMethodError: undefined method `index' for nil:NilClass

### ISSUE THREAD

**Issue by rainerborene** [gettalong/hexapdf#96]
Here's the backtrace:
```
NoMethodError: undefined method `index' for nil:NilClass
  from hexapdf/parser.rb:336:in `retrieve_pdf_header_offset_and_version'
  from hexapdf/parser.rb:62:in `initialize'
  from hexapdf/revisions.rb:66:in `new'
  from hexapdf/revisions.rb:66:in `from_io'
  from hexapdf/document.rb:137:in `initialize'
```

First you'll need to create an empty file:
```bash
$ touch something.pdf
```
Then do this in Ruby:
```ruby
file = File.open("something.pdf")
doc = HexaPDF::Document.new io: file
```

**Comment by gettalong** [comment]
Thanks - will fix this for the next release!

**Comment by gettalong** [comment]
Fixed by throwing better error messages.
